# This file is part of the Provider API Example.
#
# Copyright (C) 2023 Serghei Iakovlev <egrep@protonmail.ch>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

version: 2

updates:

  - package-ecosystem: pip
    # setup.py stored in repository root.
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - sergeyklay

  - package-ecosystem: github-actions
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - sergeyklay

  - package-ecosystem: npm
    # package.json stored in repository root.
    directory: /
    schedule:
      interval: daily
    assignees:
      - sergeyklay
